---
- hosts: all
  user: root

  vars:
    elasticsearchHost: <elasticsarchHostIP>
    kibanaHost: <kibanaHostIP>

  tasks:
    - name: Download and install the public signing key
      rpm_key:
        state: present
        key: https://packages.elastic.co/GPG-KEY-elasticsearch

    - name: Create a file with a.repo
      copy: src=config/filebeat.repo dest=/etc/yum.repos.d/filebeat.repo owner=root group=root mode=0644

    - name: install filebeat
      yum: name=filebeat state=installed

    - name: elasticsearch Host
      replace:
        dest: /etc/filebeat/filebeat.yml
        regexp: '\["localhost:9200"\]'
        replace: '["{{elasticsearchHost}}"]'

    - name: kibana Host
      replace:
        dest: /etc/filebeat/filebeat.yml
        regexp: '#host: "localhost:5601"'
        replace: 'host: "{{kibanaHost}}"'

    - name: \*.log collection true
      replace:
        dest: /etc/filebeat/filebeat.yml
        regexp: ' enabled: false'
        replace: ' enabled: true'

    - name: modules config reloading
      replace:
        dest: /etc/filebeat/filebeat.yml
        regexp: 'reload.enabled: false'
        replace: 'reload.enabled: true'

    - name: Dashboards enable true
      replace:
        dest: /etc/filebeat/filebeat.yml
        regexp: '#setup.dashboards.enabled: false'
        replace: 'setup.dashboards.enabled: true'

    - name: template setting overwrite true
      lineinfile:
        dest: /etc/filebeat/filebeat.yml
        insertafter: 'Elasticsearch template setting'
        line: 'setup.template.overwrite: true'

    - name: cp filebeat command
      command: cp /usr/share/filebeat/bin/filebeat /etc/filebeat

    - name: enable modules system
      shell: filebeat modules enable system chdir=/etc/filebeat

    - name: service start enable
      service: name=filebeat state=started enabled=yes

